### ISSUE TITLE
redmine 5.0

### ISSUE THREAD

**Issue by ashrafalzyoud** [kenan3008/redmine_issue_view_columns#13]
can u update it to redmine 5.0

**Comment by san199332** [comment]
> can u update it to redmine 5.0

Hello. Try my patched version of the plugin: https://github.com/san199332/redmine_issue_view_columns

Works in redmine 5.0.X

**Comment by cathychien** [comment]
@san199332 Thank you! It's very helpful

**Comment by ashrafalzyoud** [comment]
can u check it in redmine 5.1.1

```
[4859389e-ef9f-4067-b13a-6024649f13db] NoMethodError (undefined method `ident=' for #<IssueViewColumns id: nil, project_id: 1, name: nil, position: nil>):
[4859389e-ef9f-4067-b13a-6024649f13db]   
[4859389e-ef9f-4067-b13a-6024649f13db] plugins/redmine_issue_view_columns/app/controllers/issue_view_columns_controller.rb:22:in `block in update'
[4859389e-ef9f-4067-b13a-6024649f13db] plugins/redmine_issue_view_columns/app/controllers/issue_view_columns_controller.rb:16:in `each'
[4859389e-ef9f-4067-b13a-6024649f13db] plugins/redmine_issue_view_columns/app/controllers/issue_view_columns_controller.rb:16:in `update'
[4859389e-ef9f-4067-b13a-6024649f13db] lib/redmine/sudo_mode.rb:61:in `sudo_mode
```

**Comment by ashrafalzyoud** [comment]
mr @san199332

**Comment by ashrafalzyoud** [comment]
In redmine 5.1 
It's working in one level
If task-subtask
But if there 3 level
Task-subtask -subtask
Not working
@san199332

**Comment by ashrafalzyoud** [comment]
Any update
@san199332

**Comment by san199332** [comment]
> In redmine 5.1 It's working in one level If task-subtask But if there 3 level Task-subtask -subtask Not working @san199332

Thanks, I'll check it later and make a correction.

**Comment by san199332** [comment]
> In redmine 5.1 It's working in one level If task-subtask But if there 3 level Task-subtask -subtask Not working @san199332

I can't reproduce the error, please send me a video.
![image](https://github.com/kenandervisevic/redmine_issue_view_columns/assets/64955380/f33dca93-2a85-4f21-ad5a-188e6355dab3)

**Comment by ashrafalzyoud** [comment]
This pic in redmine 5.1?!

**Comment by san199332** [comment]
> This pic in redmine 5.1?!

```
Environment:
  Redmine version                5.1.1.stable
  Ruby version                   3.1.2-p20 (2022-04-12) [x86_64-linux]
  Rails version                  6.1.7.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
```

**Comment by ashrafalzyoud** [comment]
`
uninitialized constant IssueViewColumns::ProjectHelperPatch (NameError)
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:135:in `cget'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `each'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `ls'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:16:in `each'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:379:in `block in eager_load_all'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:377:in `each'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader.rb:377:in `eager_load_all'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/application/finisher.rb:80:in `block in <module:Finisher>'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/initializable.rb:32:in `instance_exec'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/initializable.rb:32:in `run'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/initializable.rb:60:in `run_initializers'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/application.rb:423:in `initialize!'
  /home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.8/lib/rack/builder.rb:118:in `instance_eval'
  /home/redmine/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.8/lib/rack/builder.rb:118:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'`

**Comment by ashrafalzyoud** [comment]
@san199332 plz check this error

**Comment by ashrafalzyoud** [comment]
https://github.com/sk-ys/redmine_subtask_list_accordion/tree/master
can u try this plugin
